### PR TITLE
Kb recommended products

### LINKED ISSUE #1: Add recommended products to user profile
Currently, when `/profile` is requested from the API, the products that the user has recommended to other users is included in the response.

```json
"recommends": [
    {
        "product": {
            "id": 32,
            "name": "DB9"
        },
        "customer": {
            "id": 5,
            "user": {
                "first_name": "Joe",
                "last_name": "Shepherd",
                "email": "joe@joeshepherd.com"
            }
        }
    }
]
```

This response needs to be augmented to also include the products that were recommended by another user to this user. 

1. The property should be `recommended`
2. It should be an array of recommendations that were made to the current user, not by them

```json
"recommendations": [
    {
        "product": {
            "id": 50,
            "name": "Escalade EXT"
        },
        "recommender": {
            "id": 7,
            "user": {
                "first_name": "Brenda",
                "last_name": "Long",
                "email": "brenda@brendalong.com"
            }
        }
    }
]
```

### LINKED ISSUE #22: Same user profile always returned
When an authenticated client submits a GET request to the `/profile` resource, an incorrect user profile is returned. Additionally, the same user profile is returned regardless of the authentication token provided.

### PR DESCRIPTION
**Pull request by kylieanyce**
Description of PR that completes issue here...

## Changes

- changed list method in profile viewset to bring back auth.user 
- added recommended property to customer model and profile viewset so serializer can bring back recommendations and recommenders

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Response**

HTTP/1.1 201 CREATED

```json
{
    "id": 7,
    "url": "http://localhost:8000/customers/7",
    "user": {
        "first_name": "Brenda",
        "last_name": "Long",
        "email": "brenda@brendalong.com"
    },
    "phone_number": "555-1212",
    "address": "100 Indefatiguable Way",
    "payment_types": [
        {
            "id": 3,
            "deleted": null,
            "merchant_name": "Visa",
            "account_number": "fj0398fjw0g89434",
            "expiration_date": "2020-03-01",
            "create_date": "2019-03-11",
            "customer": 7
        }
    ],
    "recommends": [
        {
            "product": {
                "id": 32,
                "name": "DB9"
            },
            "customer": {
                "id": 4,
                "user": {
                    "first_name": "Steve",
                    "last_name": "Brownlee",
                    "email": "steve@stevebrownlee.com"
                }
            },
            "recommender": {
                "id": 7,
                "user": {
                    "first_name": "Brenda",
                    "last_name": "Long",
                    "email": "brenda@brendalong.com"
                }
            }
        }
    ],
    "recommended": [
        {
            "product": {
                "id": 32,
                "name": "DB9"
            },
            "customer": {
                "id": 7,
                "user": {
                    "first_name": "Brenda",
                    "last_name": "Long",
                    "email": "brenda@brendalong.com"
                }
            },
            "recommender": {
                "id": 7,
                "user": {
                    "first_name": "Brenda",
                    "last_name": "Long",
                    "email": "brenda@brendalong.com"
                }
            }
        }
]
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [x] Seed database

## Related Issues

- Fixes #1
- Fixes #22

### CODE REVIEW

**Review by Scott47 — COMMENTED** [review]
Do you need the customer in the Recommender serializer? Looks like duplicate code to me.

**Review by Scott47 — APPROVED** [review]
👍 ready for merge!!!

**Comment by kylieanyce** [comment]
Okay, it is confusing with Brenda because she recommended a review to herself. However, they are different things. I decided to make a new serializer that brings back the product and the person who recommended.

**Comment by Scott47** [comment]
The reason you don't need both of them in the `RecommendedSerializer` is because both variables (customer and recommender) are set to a `Customer()` instance.

**Pull request merged**
