### PR TITLE
added test for delete product method

### LINKED ISSUE #8: TEST: Delete product
Write a new test in the `tests/product.py` module that verifies that a product can be deleted and not shown to users.

### LINKED ISSUE #15: Division by zero error on products
# CRITICAL ISSUE

When the client requests a single product, or all products, the status code is 500 and the response is always the following.

```
ZeroDivisionError at /products
division by zero
```

The most recent feature added by the team was adding an average rating key to each product. You might want to start there and see if there are any `try/catch` blocks you can implement.

### LINKED ISSUE #22: Same user profile always returned
When an authenticated client submits a GET request to the `/profile` resource, an incorrect user profile is returned. Additionally, the same user profile is returned regardless of the authentication token provided.

### PR DESCRIPTION
**Pull request by kylieanyce**
Description of PR that completes issue here...

## Changes

- added test for deleting a product

## Requests / Responses

n/a

## Testing

Description of how to test code...

- [ ] Run migrations
- [x] Run test suite
- [ ] Seed database

## Related Issues

- Fixes #8
- Fixes #15

### CODE REVIEW

**Review by Scott47 — APPROVED** [review]
👍 ready for merge. FYI, the test_delete_product could be dryer if you called `test_create_product()` for you product to be deleted. Just a thought. Not at all necessary. You code is correct and good.

**Comment by kylieanyce** [comment]
wow @Scott47 that's a great idea! Let me see if I can make that work...

**Comment by kylieanyce** [comment]
@Scott47 can you check this try except block and see if you think it's good to go?

**Review by Scott47 — APPROVED** [review]
👍 looks nice and dry 😄

**Pull request merged**
